name: Greetings

on: [pull_request_target, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
      - name: msg
        # You may pin to the exact commit or the version.
        # uses: GokulDas027/TelegramBridge@684649887d1b1b260e23f5afe66621e4c9f57ca0
        uses: GokulDas027/TelegramBridge@1.2
        with:
          # Chat to s@end: chat id or @channel_name/add to secrets
          chat: ${{ secrets.chat }}
          # Telegram Bot token/add to secrets
          token: ${{ secrets.token }}
          # Job status
          status: ${{ job.status }} # optional, default is ${{ job.status }}
          # Event triggered action
          event: ${{ github.event_name }} 1# optional, default is ${{ github.event_name }}
          # Actor who did the action
          actor: ${{ github.event_name }} 1# optional, default is ${{ github.actor }}
